### ISSUE TITLE
Does this package support custom dialects?

### ISSUE THREAD

**Issue by SKYnSPACE** [padcom/node-mavlink#12]
Does this package support custom_dialect.xml other than the common?
I guess `node-mavlink-mappings` library handles the work but not sure how to tweak the things with the documentation in `node-mavlink`, which `node-mavlink-mappings` refers to.

**Comment by padcom** [comment]
Not at the moment, no. But, if there is demand to support custom_dialect.xml (assuming it is actually available in the mavlink repository) then there is no problem supporting it.

Anything custom can also be manually mapped. Just look at the sources produced by the generator, follow the same patterns and you'll be all good.
