### ISSUE TITLE
Serialization error regarding uint64_t type fields

### ISSUE THREAD

**Issue by SKYnSPACE** [padcom/node-mavlink#13]
Whenever I try to serialize a payload containing uint64_t field, such as SystemTime(#2) in the common dialect, the following error arises:

node:internal/buffer:581
  let lo = Number(value & 0xffffffffn);
                        ^
TypeError: Cannot mix BigInt and other types, use explicit conversions
    at writeBigU_Int64LE (node:internal/buffer:581:25)
    at Buffer.writeBigUInt64LE (node:internal/buffer:601:10)

Are there any other protocols to follow to handle the types in 64 bits?
Thank you :)

**Comment by padcom** [comment]
64-bit numbers in Node.js are represented with BigInt. Check out the docs at https://developer.mozilla.org/pl/docs/Web/JavaScript/Reference/Global_Objects/BigInt to learn how to deal with those values.

**Comment by padcom** [comment]
It essentially means you need to use the `n` suffix :)

![image](https://user-images.githubusercontent.com/553994/175052157-05076130-65ab-4b4e-94dd-6103ba261ea2.png)

**Comment by SKYnSPACE** [comment]
Not giving any value to the time_usec (uint64_t) field produces the same error. 
Setting `msg.timeUsec` to 0n solved the issue. 

Thanks a lot 👍👍👍👍👍
