### ISSUE TITLE
Version 1.5.0 Has a Breaking Changes

### ISSUE THREAD

**Issue by emirkartal0** [padcom/node-mavlink#20]
**When we pass version 1.5.0, we get breaking changes.**  

For example changes in 
node_modules/mavlink-mappings/dist/lib/common.d.ts:10215:
`param1  change to  _param1`
or same path 
`Property 'x' does not exist on type 'CommandInt'.`

**Comment by padcom** [comment]
`CommandInt` and `CommandLong` don't have the paramX and x,y,z fields anymore and that is by design. Use proper command objects.

**Comment by padcom** [comment]
```
export const COMMANDS: MavLinkCommandRegistry = {
  [MavCmd.NAV_WAYPOINT]: NavWaypointCommand,
  [MavCmd.NAV_LOITER_UNLIM]: NavLoiterUnlimCommand,
  [MavCmd.NAV_LOITER_TURNS]: NavLoiterTurnsCommand,
  [MavCmd.NAV_LOITER_TIME]: NavLoiterTimeCommand,
  [MavCmd.NAV_RETURN_TO_LAUNCH]: NavReturnToLaunchCommand,
  [MavCmd.NAV_LAND]: NavLandCommand,
...
```

**Comment by padcom** [comment]
Since obviously it was confusing and the docs have been outdated I've made some changes to keep them more up to date.

**Comment by emirkartal0** [comment]
Great, thank you for sharing.
