### ISSUE TITLE
paramId weird output

### ISSUE THREAD

**Issue by BasvanH** [padcom/node-mavlink#27]
Hi, i'm receiving packets thru serial port from a CubeOrnage HX4. I want to read the paramId of the received packets, when outputting these the content is unreadable. I tried to figure out if its a encoding issue but I havent found it.

```
const data = packet.protocol.data(packet.payload, clazz);
const value = packet.protocol.data(packet.payload, MavLink.common.ParamValue);

if (data.hasOwnProperty('airspeed')) {
    console.log(value.paramId);
}
```

Output examples:
```
Âõh¿
{.¿
Y¿
```

Goal is to determine what type of packet is received in regards to the protocol specification.

**Comment by padcom** [comment]
@BasvanH Sorry for the late response. Parameter value management is currently not implemented. Please refer to issue #11 for details.

That #11 issue isn't closed because I still want to make the implementation better than it currently is. Much better. I'll come. One day :)
