### ISSUE TITLE
mavlink typescript error

### ISSUE THREAD

**Issue by jhong-sync** [padcom/node-mavlink#34]
`import { MAVLinkMessage } from 'node-mavlink;`
`Module '"node-mavlink"' has no exported member 'MAVLinkMessage'.ts(2305)`

In message-registry.ts, import MAVLinkMessage but node-mavlink library has no such memeber.
How to fix this situation?

Thanks!!

**Comment by padcom** [comment]
There is no such thing as `MAVLinkMessage` in this project, nor in the mavlink-mappings. Do you mind explaining how did you arrive at this problem?

**Comment by jhong-sync** [comment]
@padcom 
Thank you for your support!
First I followed instruction of this mavlink website. (https://mavlink.io/en/getting_started/generate_libraries.html)
And then I chose all.xml, typscript, 2.0 -> generate
<img width="160" alt="image" src="https://github.com/ArduPilot/node-mavlink/assets/93499791/298d7b64-544b-4ed2-b94f-0b0387880c8f">

So the result of generation was below picture.
<img width="161" alt="image" src="https://github.com/ArduPilot/node-mavlink/assets/93499791/7d62c0b9-9991-408a-8562-2c4abce6dc20">

And in message-registry.ts, I found `import {MAVLinkMessage} from 'node-mavlink';`
<img width="692" alt="image" src="https://github.com/ArduPilot/node-mavlink/assets/93499791/261c466a-de78-4bfb-b796-79fffebe3bc0">

This is how I got that code. If I had mistake let me know what I did wrong!

Thank you so much for your effort.

**Comment by padcom** [comment]
You're using the wrong library. Here are the instructions you're looking for:

https://github.com/ArduPilot/node-mavlink?tab=readme-ov-file#getting-started
