### ISSUE TITLE
Result when sending over UDP

### ISSUE THREAD

**Issue by BasvanH** [padcom/node-mavlink#38]
Hi,

Im sending packets over UDP. That seems to be working but I would like to know the different result returns I'm getting.

For instance, im requesting a MissionRequestList command.

```
var msg = new mavlink.common.MissionRequestList();
msg[targetSystem] = 0;
msg[targetComponent] = 0;
msg[seq] = 0;
msg[missionType] = 0;
const result = await mavlinkPort.send(msg);
```

I get result =12;

When I change some variables, I get 15 or 13 back. What do those numbers indicate? Is there some reference somewhere?

Thanks in advance,
Bastiaan

**Comment by padcom** [comment]
It's the number of bytes transferred over the network.
