### ISSUE TITLE
Update the documentation

### ISSUE THREAD

**Issue by wleklinskimateusz** [padcom/node-mavlink#8]
"SerialPort" library has been updated and as a result code in the documentation doesn't work. I suggest changing the docs to include said changes.
https://serialport.io/docs/api-serialport

**Comment by padcom** [comment]
Do you want to contribute a PR with that fix? Sure looks like you have found the problem and a solution that works, so I thought maybe you'll want to share?

**Comment by padcom** [comment]
Docs updated.
